# Generated by Django 3.1.1 on 2020-12-02 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_cartitem_variations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='variations',
        ),
    ]
