# Generated by Django 3.1.1 on 2020-12-02 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_cart_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
    ]
