# Generated by Django 3.1.1 on 2020-12-02 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_variation_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='category',
        ),
    ]
